### ISSUE TITLE
Can not create client without custom login page

### ISSUE THREAD

**Issue by pascalbe-dev** [dasmeta/terraform-auth0-modules#16]
Hey, 
with the recent changes in the underlying Auth0 provider, this module now causes errors when trying to create clients without custom login page.

**Steps**

1. Adding a client without custom_login_page setting
2. Running a plan
3. Running an apply

**Expected**
All is fine, all gets applied

**Actual**
The apply fails with this error message:

> Error: 400 Bad Request: Payload validation error: 'String is too short (0 chars), minimum 1' on property custom_login_page (The content (HTML, CSS, JS) of the custom login page).

**Background**
There have been bugfixes in the Auth0 provider lately described [here](https://github.com/auth0/terraform-provider-auth0/issues/360). Your auth0 module defaults the `custom_login_page` setting to an empty string. This causes errors in the underlying provider when applying. I would propose to set the default value to `null` instead of an empty string as also mentioned in the linked Github issue.

I can also create a PR, if you want.

**Comment by aghamyan44** [comment]
Fix [v1.2.7](https://github.com/dasmeta/terraform-auth0-modules/releases/tag/v1.2.7)
