### ISSUE TITLE
Configure MFA via OTP

### ISSUE THREAD

**Issue by pascalbe-dev** [dasmeta/terraform-auth0-modules#20]
**CONTEXT**
Hey, currently, it's not possible to configure MFA for all applications via the OTP method. 

**FEATURE REQUEST**
Could you please add configuration option in the module?

**RELATED INFO**
The required configuration can be found [here](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/guardian) in the official provider.

**Comment by aghamyan44** [comment]
fix https://github.com/dasmeta/terraform-auth0-modules/pull/21
